import React, { Component } from "react"
import { View, Image, Text, TouchableOpacity } from 'react-native'
import { Container, Content, Card, CardItem } from "native-base"
import styles from "../styles"
import TitleHeader from "../../../components/TitleHeader"

const products = [
  { name: "Cassis feuilles", price: "11,41", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/cassis-bio.png") },
  { name: "Jus d'Argousier", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Aloé Vera Sève", price: "14,67", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/aloe-vera-seve-bio.jpg") },
  { name: "Achillée millefeuille", price: "14,67", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/achillee-millefeuille-bio.jpg") },
  { name: "Artichaut", price: "10,37", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/artichaut-bio.jpg") },
  { name: "Armoise", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/armoise-bio.jpg") },
  { name: "Aubier de Tilleul", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/aubier-de-tilleul-bio.jpg") },
  { name: "Sève de Bouleau", price: "16,76", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/seve-de-bouleau-bio.jpg") },
  { name: "Bruyère", price: "13,52", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/bruyere-bio.jpg") },
  { name: "Chardon Marie Semence", price: "11,41", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/chardon-marie-bio.jpg") },
  { name: "Cranberry Canneberge fruit", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/cranberry-canneberge-bio.jpg") },
  { name: "Desmodium", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/desmodium-bio.jpg") },
  { name: "Valériane racine", price: "14,65", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Fumeterre", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Radis Noir racines", price: "11,41", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Ginkgo Biloba feuilles", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Pissenlit racine", price: "13,52", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Harpagophytum", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Olivier feuilles", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Millepertuis Plante entière", price: "14,17", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Marron d'Inde fruit", price: "11,41", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Pavot de Californie Plante entière flecodee", price: "14,65", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Mélisse feuilles", price: "13,52", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Reine des Prés", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Vigne Rouge feuilles", price: "11,41", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Serpolet Plante entière", price: "13,52", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Mauve Plante entière flecodee", price: "13,52", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Echinacée Plante entière flecodee", price: "15,23", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Sarriette feuilles", price: "14,65", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Prèle des Champs", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Ortie piquante Plante entière", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Lotier corniculé Plante entière", price: "14,65", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Tanaisie Plante entière", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Aloe Vera Mucilage", price: "14,67", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Myrtille feuilles", price: "13,52", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Menthe poivrée Plante entière", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Menthe Nanah feuilles", price: "12,47", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") },
  { name: "Romarin feuilles", price: "11,41", pack: "20 ampoules de 15 ml", box: "300 ml", code: require("../../../../assets/products/argousier-bio.jpg") }
]

const productsData = [
  {
    code: 3760265300112,
    img: require("../../../../assets/products/3760265300112.jpg"),
    name: "Achillée millefeuille Bio",
    intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion",
    ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.",
    composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)",
    pack: "20 ampoules buvables de 15 ml",
    completeBox: "300 ml",
    detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune."
  },
  { code: 3760265300341, img: require("../../../../assets/products/3760265300341.jpg"), name: "Aloe vera - Sève", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300013, img: require("../../../../assets/products/3760265300013.jpg"), name: "Aloe vera", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300310, img: require("../../../../assets/products/3760265300310.jpg"), name: "Jus d’argousier", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300136, img: require("../../../../assets/products/3760265300136.jpg"), name: "Artichaut", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300129, img: require("../../../../assets/products/3760265300129.jpg"), name: "Armoise", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300030, img: require("../../../../assets/products/3760265300030.jpg"), name: "Aubier de tilleul", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300303, img: require("../../../../assets/products/3760265300303.jpg"), name: "Sève de Bouleau", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300280, img: require("../../../../assets/products/3760265300280.jpg"), name: "Bruyère", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300037, img: require("../../../../assets/products/3760265300037.jpg"), name: "Cassis", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300044, img: require("../../../../assets/products/3760265300044.jpg"), name: "Chardon Marie", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300051, img: require("../../../../assets/products/3760265300051.jpg"), name: "Cranberry - Cannberge", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },

  { code: 3760265300068, img: require("../../../../assets/products/3760265300068.jpg"), name: "Desmodium", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300297, img: require("../../../../assets/products/3760265300297.jpg"), name: "Echinacée", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300358, img: require("../../../../assets/products/3760265300358.jpg"), name: "Fumeterre", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300075, img: require("../../../../assets/products/3760265300075.jpg"), name: "Ginkgo biloba", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300365, img: require("../../../../assets/products/3760265300365.jpg"), name: "Harpagophyton", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300143, img: require("../../../../assets/products/3760265300143.jpg"), name: "Lotier corniculé", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300150, img: require("../../../../assets/products/3760265300150.jpg"), name: "Marron d’Inde", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300167, img: require("../../../../assets/products/3760265300167.jpg"), name: "Mauve", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300174, img: require("../../../../assets/products/3760265300174.jpg"), name: "Mélisse", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300181, img: require("../../../../assets/products/3760265300181.jpg"), name: "Menthe nanah", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300198, img: require("../../../../assets/products/3760265300198.jpg"), name: "Menthe poivrée", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300204, img: require("../../../../assets/products/3760265300204.jpg"), name: "Millepertuis", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300082, img: require("../../../../assets/products/3760265300082.jpg"), name: "Myrtille", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },

  { code: 3760265300099, img: require("../../../../assets/products/3760265300099.jpg"), name: "Olivier", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300211, img: require("../../../../assets/products/3760265300211.jpg"), name: "Ortie", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300228, img: require("../../../../assets/products/3760265300228.jpg"), name: "Pavot de californie", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300259, img: require("../../../../assets/products/3760265300259.jpg"), name: "Pissenlit", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300372, img: require("../../../../assets/products/3760265300372.jpg"), name: "Prêle des champs", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300327, img: require("../../../../assets/products/3760265300327.jpg"), name: "Radis noir", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300389, img: require("../../../../assets/products/3760265300389.jpg"), name: "Reine des près", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300266, img: require("../../../../assets/products/3760265300266.jpg"), name: "Romarin", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300235, img: require("../../../../assets/products/3760265300235.jpg"), name: "Sariette", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300273, img: require("../../../../assets/products/3760265300273.jpg"), name: "Serpolet", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300242, img: require("../../../../assets/products/3760265300242.jpg"), name: "Tanaisie", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { code: 3760265300334, img: require("../../../../assets/products/3760265300334.jpg"), name: "Valériane", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  {
    code: 3760265300105,
    img: require("../../../../assets/products/3760265300105.jpg"),
    name: "Vigne rouge",
    intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion",
    ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.",
    composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)",
    pack: "20 ampoules buvables de 15 ml",
    completeBox: "300 ml",
    detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune."
  }
]

export default class ProductsList extends Component {

  _viewDetail = (item) => {
    this.props.navigation.navigate('ProductsDetail', { item })
  }

  render() {
    return (
      <Container style={{ backgroundColor: "#f1f2f7" }}>
        <TitleHeader title={this.props.titleHeader} navigation={this.props.navigation} />
        <Content padder>
          {productsData.map(({ code, img, name, intro, ingredients, composition, pack, completeBox, detail }, index) => {
            return (
              <Card key={index}>
                <TouchableOpacity activeOpacity={0.7} onPress={() => { this._viewDetail(code) }}>
                  <CardItem>
                    <Image style={{ width: 120, height: 200, zIndex: 999 }} source={img} />
                    <View style={{ flex: 1 }}>
                      <View style={styles.flag}>
                        <Text numberOfLines={1} style={{ color: '#fff', fontWeight: '700' }}>{name}</Text>
                        <Text numberOfLines={1} style={{ color: '#fff', fontSize: 13 }}>{pack}</Text>
                        <Text numberOfLines={1} style={{ color: '#fff', fontSize: 13 }}>Boîte complète: {completeBox}</Text>
                        <View style={styles.flagBottom} />
                      </View>
                      <View style={{ paddingLeft: 10 }}>
                        <Text style={{ color: '#7ABC9D' }}>Ingrédients :</Text>
                        <Text style={{ fontSize: 13 }}>{ingredients}</Text>
                      </View>
                    </View>
                  </CardItem>
                </TouchableOpacity>
              </Card>
            )
          }
          )}
        </Content>
      </Container >
    )
  }
}
