import React, { Component } from "react"
import { View, Image, ScrollView } from 'react-native'
import { Container, Content, Header, Button, List, ListItem, Icon, Left, Right, Thumbnail, Body, Tabs, Fab, H1, H3, Tab, Text, Card, CardItem } from "native-base"

import styles from "../styles"

const productsData = [
  {
    productCode: 3760265300112,
    img: require("../../../../assets/products/3760265300112.jpg"),
    name: "Achillée millefeuille Bio",
    intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion",
    ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.",
    composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)",
    pack: "20 ampoules buvables de 15 ml",
    completeBox: "300 ml",
    detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune."
  },
  { productCode: 3760265300341, img: require("../../../../assets/products/3760265300341.jpg"), name: "Aloe vera - Sève", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300013, img: require("../../../../assets/products/3760265300013.jpg"), name: "Aloe vera", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300310, img: require("../../../../assets/products/3760265300310.jpg"), name: "Jus d’argousier", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300136, img: require("../../../../assets/products/3760265300136.jpg"), name: "Artichaut", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300129, img: require("../../../../assets/products/3760265300129.jpg"), name: "Armoise", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300030, img: require("../../../../assets/products/3760265300030.jpg"), name: "Aubier de tilleul", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300303, img: require("../../../../assets/products/3760265300303.jpg"), name: "Sève de Bouleau", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300280, img: require("../../../../assets/products/3760265300280.jpg"), name: "Bruyère", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300037, img: require("../../../../assets/products/3760265300037.jpg"), name: "Cassis", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300044, img: require("../../../../assets/products/3760265300044.jpg"), name: "Chardon Marie", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300051, img: require("../../../../assets/products/3760265300051.jpg"), name: "Cranberry - Cannberge", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },

  { productCode: 3760265300068, img: require("../../../../assets/products/3760265300068.jpg"), name: "Desmodium", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300297, img: require("../../../../assets/products/3760265300297.jpg"), name: "Echinacée", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300358, img: require("../../../../assets/products/3760265300358.jpg"), name: "Fumeterre", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300075, img: require("../../../../assets/products/3760265300075.jpg"), name: "Ginkgo biloba", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300365, img: require("../../../../assets/products/3760265300365.jpg"), name: "Harpagophyton", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300143, img: require("../../../../assets/products/3760265300143.jpg"), name: "Lotier corniculé", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300150, img: require("../../../../assets/products/3760265300150.jpg"), name: "Marron d’Inde", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300167, img: require("../../../../assets/products/3760265300167.jpg"), name: "Mauve", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300174, img: require("../../../../assets/products/3760265300174.jpg"), name: "Mélisse", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300181, img: require("../../../../assets/products/3760265300181.jpg"), name: "Menthe nanah", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300198, img: require("../../../../assets/products/3760265300198.jpg"), name: "Menthe poivrée", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300204, img: require("../../../../assets/products/3760265300204.jpg"), name: "Millepertuis", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300082, img: require("../../../../assets/products/3760265300082.jpg"), name: "Myrtille", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },

  { productCode: 3760265300099, img: require("../../../../assets/products/3760265300099.jpg"), name: "Olivier", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300211, img: require("../../../../assets/products/3760265300211.jpg"), name: "Ortie", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300228, img: require("../../../../assets/products/3760265300228.jpg"), name: "Pavot de californie", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300259, img: require("../../../../assets/products/3760265300259.jpg"), name: "Pissenlit", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300372, img: require("../../../../assets/products/3760265300372.jpg"), name: "Prêle des champs", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300327, img: require("../../../../assets/products/3760265300327.jpg"), name: "Radis noir", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300389, img: require("../../../../assets/products/3760265300389.jpg"), name: "Reine des près", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300266, img: require("../../../../assets/products/3760265300266.jpg"), name: "Romarin", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300235, img: require("../../../../assets/products/3760265300235.jpg"), name: "Sariette", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300273, img: require("../../../../assets/products/3760265300273.jpg"), name: "Serpolet", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300242, img: require("../../../../assets/products/3760265300242.jpg"), name: "Tanaisie", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  { productCode: 3760265300334, img: require("../../../../assets/products/3760265300334.jpg"), name: "Valériane", intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion", ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.", composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)", pack: "20 ampoules buvables de 15 ml", completeBox: "300 ml", detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune." },
  {
    productCode: 3760265300105,
    img: require("../../../../assets/products/3760265300105.jpg"),
    name: "Vigne rouge",
    intro: "Chez les femmes, apaise les crampes abdominales périodiques - Aide à favoriser la digestion",
    ingredients: "Extrait de plante entière d'achillée millefeuille Bio* 100%. Convient aux Vegans. *100% des ingrédients agricoles sont issus de l’Agriculture Biologique.",
    composition: "Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)",
    pack: "20 ampoules buvables de 15 ml",
    completeBox: "300 ml",
    detail: "L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune."
  }
]
export default class ProductsList extends Component {

  _onBack() {
    this.props.navigation.navigate('ProductsList')
  }
  render() {
    const { navigation } = this.props
    let productCode = 3760265300334
    if (navigation.state.params != undefined && navigation.state.params.item != undefined) {
      productCode = navigation.state.params.item
    }
    const productItem = productsData.find((item) => item.productCode === productCode)
    return (
      <Container style={{ backgroundColor: "#f1f2f7" }}>
        <Header style={{ backgroundColor: "#92C7A9", paddingTop: 25 }} >
          <Left style={{ flex: 0.2 }}>
            <Button transparent onPress={() => this._onBack()}>
              <Icon name='arrow-back' style={{ color: "#fff", fontSize: 30 }} />
            </Button>
          </Left>
          <Body>
            <Text style={{ color: "#FFF", fontSize: 20, fontWeight: "700" }}>{productItem.name}</Text>
          </Body>
          <Right style={{ flex: 0.2 }} />
        </Header>
        <Content style={{ backgroundColor: "white" }}>
          <CardItem cardBody style={{ paddingTop: 20 }}>
            <Image style={{ resizeMode: "cover", width: null, height: 300, flex: 1 }} source={productItem.img} />
          </CardItem>
          <CardItem>
            <Body>
              <Text note>{productItem.pack}</Text>
              <Text note>{productItem.completeBox}</Text>
            </Body>
          </CardItem>
          <CardItem>
            <Body>
              <Text>Ingrédients</Text>
              <Text note>{productItem.ingredients}</Text>
              <Text note>L’achillée millefeuille est une plante vivace à racine rampante. Les tiges sont pubescentes, laineuses et blanchâtres. Les feuilles sont très découpées et de couleur vert foncé. La floraison a lieu entre juin et septembre : les fleurs regroupées en capitules sont de couleur blanche, rose ou pourpre et portent en leur cœur des fleurons blanc-jaune à jaune.</Text>
            </Body>
          </CardItem>
          <CardItem>
            <Body>
              <Text>Composition</Text>
              <Text note>{productItem.composition}</Text>
              <Text note> Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)</Text>
            </Body>
          </CardItem>
          <CardItem>
            <Body>
              <Text>Détail</Text>
              <Text note>{productItem.detail}</Text>
              <Text note> Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)</Text>
            </Body>
          </CardItem>
          <CardItem>
            <Body>
              <Text>Composition</Text>
              <Text note> Achillée millefeuille Bio : 2000mg** par ampoule de 15ml ** équivalent en plante sèches (EPS)</Text>
            </Body>
          </CardItem>
          <CardItem style={{ paddingBottom: 20 }}>
            <Body>
              <H3 style={[styles.mb10, { color: "#85cdb4" }]}> CARTON : 12 UNITÉS. </H3>
            </Body>
          </CardItem>
        </Content>
      </Container >
    )
  }
}
